In [1]:
import numpy as np

In [18]:
embeddings = np.random.normal(size=(10, 5))

In [24]:
embeddings

array([[ 0.45894408, -1.317206  ,  0.6890764 , -1.32005195, -2.31065768],
       [-1.77047533,  0.16375706,  0.13696001, -0.13418462, -1.20187151],
       [ 0.47361168,  0.79091893, -0.59874193, -0.04955534,  1.29060524],
       [ 0.86510115,  0.12529306,  1.8991957 , -0.19993309, -0.16997837],
       [ 0.03510945, -1.18289116, -0.2783095 ,  1.87130192, -1.93057107],
       [-0.29761429, -1.01485565,  1.48870612,  0.11602566, -1.11814808],
       [ 1.86616575,  1.09846796,  0.18027118,  0.06537232, -0.43486204],
       [-0.75221905, -1.1137328 , -1.13584282,  0.76298029,  0.36180221],
       [ 2.29918801,  0.13063226, -0.38957124,  1.98999769,  0.8208978 ],
       [-1.73178514, -0.3797913 , -0.22523103,  0.92242798, -0.62564918]])

In [11]:
from sklearn.metrics.pairwise import euclidean_distances


In [20]:
distance = euclidean_distances(embeddings[:2])
distance

array([[0.        , 3.17869204],
       [3.17869204, 0.        ]])

In [16]:
distance.mean(axis=1)

array([1.85881676, 1.50602996, 1.78505533, 1.78998545, 1.73439825,
       1.57798906, 2.99153249, 1.40374508, 1.27200272, 1.44789515])

In [31]:
embeddings[:, :2]

array([[ 0.45894408, -1.317206  ],
       [-1.77047533,  0.16375706],
       [ 0.47361168,  0.79091893],
       [ 0.86510115,  0.12529306],
       [ 0.03510945, -1.18289116],
       [-0.29761429, -1.01485565],
       [ 1.86616575,  1.09846796],
       [-0.75221905, -1.1137328 ],
       [ 2.29918801,  0.13063226],
       [-1.73178514, -0.3797913 ]])

In [27]:
distance = euclidean_distances(embeddings[:, :3])
distance

ValueError: Expected 2D array, got 1D array instead:
array=[-1.32005195 -0.13418462 -0.04955534 -0.19993309  1.87130192  0.11602566
  0.06537232  0.76298029  1.98999769  0.92242798].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
uniqueness = np.mean(distance, axis=1)
uniqueness

In [32]:
from sklearn.neighbors import KernelDensity

In [34]:
kde = KernelDensity(kernel='gaussian')

In [35]:
kde.fit(embeddings)

KernelDensity()

In [39]:
uniqueness_score = kde.score_samples(embeddings)
uniqueness_score

array([-6.79147156, -6.4916026 , -6.77848085, -6.66917026, -6.79805151,
       -6.56781091, -6.73026125, -6.65497583, -6.84381854, -6.38337096])

In [41]:
1 / np.exp(uniqueness_score)

array([890.22261122, 659.57955791, 878.73278554, 787.74171482,
       896.09954881, 711.8099221 , 837.36600085, 776.63915059,
       938.06434523, 591.91968836])