In [3]:
import pandas as pd

In [1]:
import numpy as np

# Исходные данные
data = {
    'age': [76, 69, 19, 31, 18, 51, 67, 27, 61, 61],
    'income': [32181, 52789, 70535, 85271, 19974, 74128, 34922, 54154, 76998, 41396],
    'dependents': [3, 8, 1, 1, 2, 3, 10, 1, 8, 5],
    'has_property': [0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    'has_car': [1, 0, 1, 1, 1, 1, 1, 1, 0, 0],
    'credit_score': [814, 501, 325, 525, 618, 551, 657, 740, 869, 636],
    'job_tenure': [28, 28, 26, 29, 34, 14, 19, 38, 35, 6],
    'has_education': [1, 1, 1, 1, 1, 0, 0, 1, 1, 0],
    'loan_amount': [142434, 120887, 188766, 406792, 155240, 257944, 207532, 229763, 147957, 483916],
    'loan_term': [1770, 1590, 810, 330, 1560, 420, 240, 660, 90, 120],
    'delay_days': [0, 7, 0, 0, 43, 0, 3, 0, 0, 12]
}

# Преобразование в ndarray
X = np.array([data['age'], data['income'], data['dependents'], data['has_property'],
              data['has_car'], data['credit_score'], data['job_tenure'], data['has_education'],
              data['loan_amount'], data['loan_term']]).T

y = np.array(data['delay_days'])

# Вывод результата
print("Матрица признаков X:")
print(X)
print("\nВектор целевой переменной y:")
print(y)


Матрица признаков X:
[[    76  32181      3      0      1    814     28      1 142434   1770]
 [    69  52789      8      1      0    501     28      1 120887   1590]
 [    19  70535      1      0      1    325     26      1 188766    810]
 [    31  85271      1      0      1    525     29      1 406792    330]
 [    18  19974      2      0      1    618     34      1 155240   1560]
 [    51  74128      3      0      1    551     14      0 257944    420]
 [    67  34922     10      1      1    657     19      0 207532    240]
 [    27  54154      1      0      1    740     38      1 229763    660]
 [    61  76998      8      0      0    869     35      1 147957     90]
 [    61  41396      5      0      0    636      6      0 483916    120]]

Вектор целевой переменной y:
[ 0  7  0  0 43  0  3  0  0 12]


In [8]:
X[:, 0]

array([76, 69, 19, 31, 18, 51, 67, 27, 61, 61])

In [6]:
X[0]

array([    76,  32181,      3,      0,      1,    814,     28,      1,
       142434,   1770])

In [28]:
import numpy as np

original_list = X[:, 0]

# Значение, по которому разделяем список
split_value = 31

# Преобразуем список в массив NumPy
arr = np.array(original_list)

# Находим индексы, по которым разделяем массив
split_indices = np.where(arr == split_value)[0]

# Разделяем массив на части
if len(split_indices) > 0:
    split_index = split_indices[0]
    first_part, second_part = arr[:split_index], arr[split_index + 1:]
else:
    first_part, second_part = arr, np.array([])

# Преобразуем обратно в списки, если это необходимо
first_part_list = first_part.tolist()
second_part_list = second_part.tolist()

print("Первая часть:", first_part_list)
print("Вторая часть:", second_part_list)


Первая часть: [76, 69, 19]
Вторая часть: [18, 51, 67, 27, 61, 61]


In [35]:
indexes_below_split_value = np.where(arr < split_value)[0]
indexes_above_split_value = np.where(arr >= split_value)[0]
print("Индексы элементов ниже", split_value, ":", indexes_below_split_value)
print("Индексы элементов не ниже", split_value, ":", indexes_above_split_value)

Индексы элементов ниже 40 : [2 3 4 7]
Индексы элементов не ниже 40 : [0 1 5 6 8 9]


In [52]:
np.array(y[indexes_above_split_value])

array([ 0,  7,  0,  3,  0, 12])

In [83]:
import numpy as np


def split(X: np.ndarray, y: np.ndarray, feature: int) -> float:
    """Find the best split for a node (one feature)"""

    split_elements = X[:, feature]

    best_split = {}
    for i in split_elements:
        indexes_below_split_value = np.where(split_elements <= i)[0]
        indexes_above_split_value = np.where(split_elements > i)[0]

        y_left = np.array(y[indexes_below_split_value])
        y_right = np.array(y[indexes_above_split_value])

        mse = weighted_mse(y_left, y_right)
        best_split[i] = mse

    max_key = min(best_split, key=best_split.get)

    return max_key


def mse(y: np.ndarray) -> np.ndarray:
    """Compute the mean squared error of a vector."""

    y_pred = np.mean(y)

    return np.mean((y - y_pred) ** 2)


def weighted_mse(y_left: np.ndarray, y_right: np.ndarray) -> float:
    """Compute the weighted mean squared error of two vectors."""
    y_left_size = y_left.size
    y_right_size = y_right.size
    return (mse(y_left) * y_left_size + mse(y_right) * y_right_size) / (y_right_size + y_left_size)


In [81]:
%%timeit
print(split(X, y, 0))

13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
1

In [78]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24], [25, 26, 27], [28, 29, 30]])
y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [82]:
%%timeit
split(X, y, 0)

161 µs ± 574 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [85]:
%%timeit
split(X, y, 0)

188 µs ± 43.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
