In [1]:
import pandas as pd

In [2]:
import numpy as np

# Исходные данные
data = {
    'age': [76, 69, 19, 31, 18, 51, 67, 27, 61, 61],
    'income': [32181, 52789, 70535, 85271, 19974, 74128, 34922, 54154, 76998, 41396],
    'dependents': [3, 8, 1, 1, 2, 3, 10, 1, 8, 5],
    'has_property': [0, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    'has_car': [1, 0, 1, 1, 1, 1, 1, 1, 0, 0],
    'credit_score': [814, 501, 325, 525, 618, 551, 657, 740, 869, 636],
    'job_tenure': [28, 28, 26, 29, 34, 14, 19, 38, 35, 6],
    'has_education': [1, 1, 1, 1, 1, 0, 0, 1, 1, 0],
    'loan_amount': [142434, 120887, 188766, 406792, 155240, 257944, 207532, 229763, 147957, 483916],
    'loan_term': [1770, 1590, 810, 330, 1560, 420, 240, 660, 90, 120],
    'delay_days': [0, 7, 0, 0, 43, 0, 3, 0, 0, 12]
}

# Преобразование в ndarray
X = np.array([data['age'], data['income'], data['dependents'], data['has_property'],
              data['has_car'], data['credit_score'], data['job_tenure'], data['has_education'],
              data['loan_amount'], data['loan_term']]).T

y = np.array(data['delay_days'])

# Вывод результата
print("Матрица признаков X:")
print(X)
print("\nВектор целевой переменной y:")
print(y)


Матрица признаков X:
[[    76  32181      3      0      1    814     28      1 142434   1770]
 [    69  52789      8      1      0    501     28      1 120887   1590]
 [    19  70535      1      0      1    325     26      1 188766    810]
 [    31  85271      1      0      1    525     29      1 406792    330]
 [    18  19974      2      0      1    618     34      1 155240   1560]
 [    51  74128      3      0      1    551     14      0 257944    420]
 [    67  34922     10      1      1    657     19      0 207532    240]
 [    27  54154      1      0      1    740     38      1 229763    660]
 [    61  76998      8      0      0    869     35      1 147957     90]
 [    61  41396      5      0      0    636      6      0 483916    120]]

Вектор целевой переменной y:
[ 0  7  0  0 43  0  3  0  0 12]


In [8]:
X[:, 0]

array([76, 69, 19, 31, 18, 51, 67, 27, 61, 61])

In [6]:
X[0]

array([    76,  32181,      3,      0,      1,    814,     28,      1,
       142434,   1770])

In [28]:
import numpy as np

original_list = X[:, 0]

# Значение, по которому разделяем список
split_value = 31

# Преобразуем список в массив NumPy
arr = np.array(original_list)

# Находим индексы, по которым разделяем массив
split_indices = np.where(arr == split_value)[0]

# Разделяем массив на части
if len(split_indices) > 0:
    split_index = split_indices[0]
    first_part, second_part = arr[:split_index], arr[split_index + 1:]
else:
    first_part, second_part = arr, np.array([])

# Преобразуем обратно в списки, если это необходимо
first_part_list = first_part.tolist()
second_part_list = second_part.tolist()

print("Первая часть:", first_part_list)
print("Вторая часть:", second_part_list)


Первая часть: [76, 69, 19]
Вторая часть: [18, 51, 67, 27, 61, 61]


In [35]:
indexes_below_split_value = np.where(arr < split_value)[0]
indexes_above_split_value = np.where(arr >= split_value)[0]
print("Индексы элементов ниже", split_value, ":", indexes_below_split_value)
print("Индексы элементов не ниже", split_value, ":", indexes_above_split_value)

Индексы элементов ниже 40 : [2 3 4 7]
Индексы элементов не ниже 40 : [0 1 5 6 8 9]


In [52]:
np.array(y[indexes_above_split_value])

array([ 0,  7,  0,  3,  0, 12])

In [86]:
from __future__ import annotations

import numpy as np


def mse(y: np.ndarray) -> float:
    """Compute the mse impurity criterion for a given set of target values."""
    return np.mean((y - np.mean(y)) ** 2)


def weighted_mse(y_left: np.ndarray, y_right: np.ndarray) -> float:
    """Compute the weighted mse criterion for a given set of target values."""
    num = mse(y_left) * y_left.size + mse(y_right) * y_right.size
    den = y_left.size + y_right.size
    return num / den


def split(X: np.ndarray, y: np.ndarray, feature: int) -> float:
    """Find the best split for a node."""
    node_size = y.size
    if node_size < 2:
        return None, None

    node_mse = mse(y)
    best_mse = node_mse
    best_thr = None

    thresholds = np.unique(X[:, feature])
    for thr in thresholds:
        left = y[X[:, feature] <= thr]
        right = y[X[:, feature] > thr]

        if left.size == 0 or right.size == 0:
            continue

        weihted_mse = weighted_mse(left, right)
        if weihted_mse < best_mse:
            best_mse = weihted_mse
            best_thr = thr

    return best_thr


In [50]:
X = np.array([[50, 2, 3], [20, 5, 6], [100, 8, 9], [35, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24],
              [25, 26, 27], [28, 29, 30]])
y = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])


In [82]:
% % timeit
split(X, y, 0)

161 µs ± 574 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [85]:
% % timeit
split(X, y, 0)

188 µs ± 43.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [87]:
% % timeit
split(X, y, 0)

147 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [101]:
X.shape[1]

3

In [102]:
import numpy as np


def mse(y: np.ndarray) -> float:
    """Compute the mse impurity criterion for a given set of target values."""
    return np.mean((y - np.mean(y)) ** 2)


def weighted_mse(y_left: np.ndarray, y_right: np.ndarray) -> float:
    """Compute the weighted mse criterion for a given set of target values."""
    num = mse(y_left) * y_left.size + mse(y_right) * y_right.size
    den = y_left.size + y_right.size
    return num / den


def best_split(X: np.ndarray, y: np.ndarray) -> tuple[int, float]:
    """Find the best split for a node."""
    node_size = y.size
    if node_size < 2:
        return None, None

    node_mse = mse(y)
    best_mse = node_mse
    best_thr = None
    best_feature = None
    for feature in range(X.shape[1]):
        thresholds = np.unique(X[:, feature])
        for thr in thresholds:
            left = y[X[:, feature] <= thr]
            right = y[X[:, feature] > thr]

            if left.size == 0 or right.size == 0:
                continue

            weihted_mse = weighted_mse(left, right)
            if weihted_mse < best_mse:
                best_mse = weihted_mse
                best_thr = thr
                best_feature = feature

    return best_feature, best_thr


In [107]:
best_split(X, y)

C:\Users\Neesty\AppData\Local\pypoetry\Cache\virtualenvs\ml-sim-kc-8z4rnjSt-py3.11\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\Neesty\AppData\Local\pypoetry\Cache\virtualenvs\ml-sim-kc-8z4rnjSt-py3.11\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


(0, 13)

In [104]:
for feature in range(X.shape[1]):
    print(feature)
    thresholds = np.unique(X[:, feature])
    print(thresholds)

0
[ 1  4  7 10 13 16 19 22 25 28]
1
[ 2  5  8 11 14 17 20 23 26 29]
2
[ 3  6  9 12 15 18 21 24 27 30]


In [3]:
import numpy as np


def mse(y: np.ndarray) -> float:
    """Compute the mse impurity criterion for a given set of target values."""
    if len(y) == 0:
        return 0.0
    return np.mean((y - np.mean(y)) ** 2)


def weighted_mse(y_left: np.ndarray, y_right: np.ndarray) -> float:
    """Compute the weighted mse criterion for a given set of target values."""
    num = mse(y_left) * y_left.size + mse(y_right) * y_right.size
    den = y_left.size + y_right.size
    return num / den


def best_split(X: np.ndarray, y: np.ndarray) -> tuple[int, float]:
    """Find the best split for a node."""

    best_split = {}
    for feature in range(X.shape[1]):
        split_elements = X[:, feature]

        best_split_1_future = {}
        for i in split_elements:
            indexes_below_split_value = np.where(split_elements <= i)[0]
            indexes_above_split_value = np.where(split_elements > i)[0]

            y_left = np.array(y[indexes_below_split_value])
            y_right = np.array(y[indexes_above_split_value])

            mse = weighted_mse(y_left, y_right)
            best_split_1_future[i] = mse

        best_split[feature] = min(best_split_1_future, key=best_split_1_future.get)

    best_feature, best_thr = min(best_split.items(), key=lambda x: x[1])

    return best_feature, best_thr


In [6]:
best_split(X, y)

(0, 13)

In [7]:
left = X[X[:, 0] <= 13], y[X[:, 0] <= 13]
right = X[X[:, 0] > 13], y[X[:, 0] > 13]

In [8]:
print(left, right)

(array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]]), array([1, 2, 3, 4, 5])) (array([[16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]]), array([ 6,  7,  8,  9, 10]))


In [9]:
X, y

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [65]:
from decision_tree_regressor import DecisionTreeRegressor

In [71]:
decisionTreeRegressor3 = DecisionTreeRegressor(max_depth=2)

In [91]:
model = decisionTreeRegressor3.fit(X, y)

sdf2
Node(feature=None, threshold=None, n_samples=10, value=55.0, mse=825.0, left=None, right=None)
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
Node(feature=None, threshold=None, n_samples=5, value=30.0, mse=200.0, left=None, right=None)
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
Node(feature=None, threshold=None, n_samples=2, value=15.0, mse=25.0, left=None, right=None)
Node(feature=None, threshold=None, n_samples=3, value=40.0, mse=66.66666666666667, left=None, right=None)
Node(feature=None, threshold=None, n_samples=5, value=80.0, mse=200.0, left=None, right=None)
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
sdf
Node(feature=None, threshold=None, n_samples=2, value=65.0, mse=25.0, left=None, right=None)
Node(feature=None, threshold=None, n_samples=3, value=90.0, mse=66.66666666666667, left=None, right=None)


C:\Users\Neesty\AppData\Local\pypoetry\Cache\virtualenvs\ml-sim-kc-8z4rnjSt-py3.11\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\Neesty\AppData\Local\pypoetry\Cache\virtualenvs\ml-sim-kc-8z4rnjSt-py3.11\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


In [89]:
from decision_tree_regressor import DecisionTreeRegressor

In [90]:
DecisionTreeRegressor.tree_

AttributeError: type object 'DecisionTreeRegressor' has no attribute 'tree_'

In [19]:
type(model)

decision_tree_regressor.DecisionTreeRegressor

In [92]:
model.tree_

Node(feature=1, threshold=14, n_samples=10, value=55.0, mse=825.0, left=Node(feature=1, threshold=5, n_samples=5, value=30.0, mse=200.0, left=Node(feature=None, threshold=None, n_samples=2, value=15.0, mse=25.0, left=None, right=None), right=Node(feature=None, threshold=None, n_samples=3, value=40.0, mse=66.66666666666667, left=None, right=None)), right=Node(feature=0, threshold=19, n_samples=5, value=80.0, mse=200.0, left=Node(feature=None, threshold=None, n_samples=2, value=65.0, mse=25.0, left=None, right=None), right=Node(feature=None, threshold=None, n_samples=3, value=90.0, mse=66.66666666666667, left=None, right=None)))

In [21]:
model

DecisionTreeRegressor(max_depth=3, min_samples_split=2)

In [235]:
@dataclass
class Node:
    """Decision tree node."""
    feature: int = None
    # YOUR CODE HERE: add the required attributes
    threshold: float = None
    n_samples: int = None
    value: int = None
    mse: int = None
    left: Node = None
    right: Node = None


NameError: name 'dataclass' is not defined

In [236]:
def _split_node(self, X: np.ndarray, y: np.ndarray, depth: int = 0) -> Node:
    """Split a node and return the resulting left and right child nodes."""
    node = Node()
    node.n_samples = y.size
    node.value = np.floor(np.mean(y))
    node.mse = self._mse(y)
    print(node)
    if depth == self.max_depth or y.size < self.min_samples_split:
        return node
    node.feature, node.threshold = self._best_split(X, y)
    depth += 1
    if node.threshold is not None:
        node.left = self._split_node(X[X[:, node.feature] <= node.threshold],
                                     y[X[:, node.feature] <= node.threshold], depth)
        node.right = self._split_node(X[X[:, node.feature] > node.threshold],
                                      y[X[:, node.feature] > node.threshold], depth)

    else:
        return node
    return node

In [76]:
test_mse = [ 0,  7,  0,  0, 43,  0,  3,  0,  0, 12,  8, 32, 35,  1,  0, 12,  0, 28, 15, 1, 22,  4, 10,  5,
  0,  0, 39,  4, 18, 27,  1,  6, 19, 20, 10, 24,  0,  0, 10,  0, 37,  0, 60, 1,  5,  0,  1,  0,
 85, 24]

In [78]:
mse(test_mse)

303.84360000000004

In [81]:
import json

# Ваш список данных
your_list = [1, 2, 3, "four", "five", {"key": "value"}]

# Преобразование списка в JSON
json_data = json.dumps(your_list)

# Вывод результата
print(json_data)


[1, 2, 3, "four", "five", {"key": "value"}]


In [116]:
import json

class Node:
    def __init__(self, feature=None, threshold=None, n_samples=0, value=None, mse=None, left=None, right=None):
        self.feature = feature
        self.threshold = threshold
        self.n_samples = n_samples
        self.value = value
        self.mse = mse
        self.left = left
        self.right = right

    def _generate_json(self, node):
        if node.left is None and node.right is None:
            return {
                'n_samples': node.n_samples,
                'value': node.value,
                'mse': node.mse
            }
        else:
            return {
                'feature': node.feature,
                'threshold': node.threshold,
                'n_samples': node.n_samples,
                'value': node.value,
                'mse': node.mse,
                'left': self._generate_json(node.left),
                'right': self._generate_json(node.right)
            }

# Создаем экземпляр класса Node (пример дерева)
root_node = Node(feature=2, threshold=49473, n_samples=50, value=13, mse=303.84360000000004, left=Node(feature=9, threshold=587589, n_samples=25, value=23, mse=367.54240000000004, left=Node(feature=None, threshold=None, n_samples=24, value=21, mse=217.30555555555554, left=None, right=None), right=Node(feature=None, threshold=None, n_samples=1, value=85, mse=0.0, left=None, right=None)), right=Node(feature=2, threshold=65813, n_samples=25, value=2, mse=12.8736, left=Node(feature=None, threshold=None, n_samples=7, value=6, mse=20.69387755102041, left=None, right=None), right=Node(feature=None, threshold=None, n_samples=18, value=0, mse=0.2006172839506173, left=None, right=None)))


# Генерируем JSON для корневой ноды и преобразуем в строку
json_data = json.dumps(root_node._generate_json(root_node), indent=2)
# print(type(root_node))
# Вывод результата
print(json.loads(json_data))


{'feature': 2, 'threshold': 49473, 'n_samples': 50, 'value': 13, 'mse': 303.84360000000004, 'left': {'feature': 9, 'threshold': 587589, 'n_samples': 25, 'value': 23, 'mse': 367.54240000000004, 'left': {'n_samples': 24, 'value': 21, 'mse': 217.30555555555554}, 'right': {'n_samples': 1, 'value': 85, 'mse': 0.0}}, 'right': {'feature': 2, 'threshold': 65813, 'n_samples': 25, 'value': 2, 'mse': 12.8736, 'left': {'n_samples': 7, 'value': 6, 'mse': 20.69387755102041}, 'right': {'n_samples': 18, 'value': 0, 'mse': 0.2006172839506173}}}
